{{/*
Purpose:
- IRSA ServiceAccount used by External Secrets Operator to read SSM parameters.
- Hooked to run before chart install/upgrade so SecretStore/ExternalSecrets can reference it.
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-11"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if .Values.irsa.externalSecrets }}
    eks.amazonaws.com/role-arn: {{ .Values.irsa.externalSecrets | quote }}
    {{- end }}
