{{/*
Purpose:
- ClusterIP Service for Jobs.
*/}}

{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jobs
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.jobs.service.type }}
  selector:
    app: jobs
  ports:
    - port: {{ .Values.jobs.service.port }}
      targetPort: {{ .Values.jobs.service.port }}
      name: http
{{- end }}
