{{/*
Purpose:
- ClusterIP Service for Reviews.
*/}}

{{- if .Values.reviews.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.reviews.service.type }}
  selector:
    app: reviews
  ports:
    - port: {{ .Values.reviews.service.port }}
      targetPort: {{ .Values.reviews.service.port }}
      name: http
{{- end }}
